package com.aslmmovic.qurancompanion

import com.aslmmovic.qurancompanion.fakes.FakeNotificationScheduler as ActualFakeNotificationScheduler

typealias FakeNotificationScheduler = ActualFakeNotificationScheduler
