package com.aslmmovic.qurancompanion

import com.aslmmovic.qurancompanion.fakes.FakeUserPreferencesRepository as ActualFakeUserPreferencesRepository

typealias FakeUserPreferencesRepository = ActualFakeUserPreferencesRepository
